Review request for re-former project
chrystalme/re-former-project pull request #1
Opened 2021-02-18 16:13 UTC by chrystalme

# Re-former project

- To create a form in rails using form_with, form_tag, form_for
- Using form partials

2021-02-18 20:09 UTC, whiz25 requested changes
## Changes Required :pray:
Nice work on this PR. You managed to set the project app and modeled the user data properly. Well done!
Lets however, make some changes before we can merge.

 - [ ] Right now the app is unable to create a new user and update the user created. Check my comments form suggestions.

### Next Projects
Follow the following guidelines in your next projects.
- [ ] Be consistent in your commit messages: `add 'forM_with' '` and `Update README.md` are quite different in format. The accepted format is to capitalize the first letter of the commit message like this: `Add 'form_with'`

### Martin Afani

2021-02-18 20:09 UTC, whiz25 commented on README.md
> +   - use ``` https://github.com/chrystalme/re-former-project.git ``` to clone the repository
- Add explicit command for cloning: `git clone ...`
- How does one start the project after cloning? Add instructions for changing to the `feature/re-former` branch, installing `yarn`, install packages using `yarn install`, bundling gems in rails, starting the rails server and migrating the database

2021-02-18 20:09 UTC, whiz25 commented on README.md
> +   - run ```bundle install ``` to install dependencies
- Add instruction for checking out the `feature/re-former` branch before install gems.

2021-02-18 20:09 UTC, whiz25 commented on app/controllers/users_controller.rb
> +    @user = User.new(username: params[:username], email: params[:email], password: params[:password])
- This is redundant. You already have logic for this in `user_params` method
```ruby
@user = User.new(user_params)
```

2021-02-18 20:09 UTC, whiz25 commented on app/controllers/users_controller.rb
> +      redirect_to @user
- Change this to `redirect_to edit_user_path`

2021-02-18 20:09 UTC, whiz25 commented on app/controllers/users_controller.rb
> +  # end
- Remove this comment. I makes your codebase look ugly.

2021-02-18 20:09 UTC, whiz25 commented on app/views/users/new.html.erb
> +<%# </form> %>
- This form is not properly commented out. A simple trick is to highlight the code then press and hold `CTRL+/`
Below is a properly commented out code:
```ruby
# <%= form_with model: @user do |form| %>
#     <%= label_tag(:username, "Username:") %><br>
#     <%= form.text_field :username %><br><br>
#     <%= label_tag(:email, "email:") %><br>
#     <%= form.email_field :email %><br><br>
#     <%= label_tag(:password, "Password:") %><br>
#     <%= form.password_field :password %><br><br>
#     <%= form.submit :Submit %>
# <% end %>
```

2021-02-18 20:09 UTC, whiz25 commented on app/views/users/new.html.erb
> +<%# <% end %>
- Properly comment out this code. See suggestion above.

2021-02-18 20:09 UTC, whiz25 commented on app/views/users/new.html.erb
> +<a href="/">Go Back</a>
- You are lacking the form for actually creating the user using `form_for`
Please add a new form for creating a user:
```ruby
<%= form_with @user do |u|%> <%= u.label :username %> <%= u.text_field :username%> 
<%= u.label :email %> 
<%= u.email_field :email %> 
<%= u.label :password %>
<%= u.password_field :password %> 
<%= u.submit %> <% end %>
```

2021-02-18 20:09 UTC, whiz25 commented on app/views/users/_form.html.erb
> +<% end %>
- Move the code form here to `new.html`

2021-02-19 03:00 UTC, SmithVyne commented on app/views/users/new.html.erb
> +<%= form_for(@user) do |form|%>
Remove the `form_for` tag and render your `form` partial here instead. Hint:
`<%= render 'form'%>`

2021-02-19 03:01 UTC, SmithVyne requested changes
### Changes Required 👍 🤕 
Hello, congratulations on making the changes requested by the previous TSE but you need to make a few more improvements to this project to this project to get it approved.
[REQUIRED] - Use the `users_path` route available in Rails instead of `/users` in all your forms.
[REQUIRED] - You should be using the `form_with` tag instead of the `form_for` tag in the new users view.

You can reach out to me on slack, @smithvyne if you have any more questions.

2021-02-19 07:08 UTC, whiz25 approved these changes
## Approved ✅ 
Well done working on the requested changes. A user can now signup and edit their details. Merge and proceed to the next project.


### Martin Afani

2021-02-19 07:19 UTC, merged